const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const { ShumaDB } = require('../models/ShumaDB');

/**
 * POST /api/export/pdf
 * Generate a PDF valuation report
 */
router.post('/pdf', async (req, res) => {
  try {
    const { sessionId, valuationData } = req.body;

    if (!sessionId) {
      return res.status(400).json({
        success: false,
        error: 'Missing sessionId'
      });
    }

    console.log(`📄 Generating PDF for session: ${sessionId}`);

    // If valuationData not provided, load from database
    let data = valuationData;
    if (!data) {
      const loadResult = await ShumaDB.loadShumaForWizard(sessionId);
      if (!loadResult.success || !loadResult.valuationData) {
        return res.status(404).json({
          success: false,
          error: 'Session not found'
        });
      }
      data = loadResult.valuationData;
    }

    // Create PDF document
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 50, bottom: 50, left: 72, right: 72 }
    });

    // Set response headers for PDF download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="shamay-valuation-${sessionId}.pdf"`);

    // Pipe PDF to response
    doc.pipe(res);

    // Add RTL support for Hebrew (requires a Hebrew font)
    // For now, we'll use a simple left-to-right layout
    // TODO: Add proper Hebrew font support (e.g., Alef, Rubik, Assistant)

    // Title
    doc.fontSize(24).text('Shamay Valuation Report', { align: 'center' });
    doc.moveDown();

    // Session Info
    doc.fontSize(12).text(`Session ID: ${sessionId}`);
    doc.text(`Generated: ${new Date().toLocaleString('he-IL')}`);
    doc.moveDown();

    // Property Details
    doc.fontSize(16).text('Property Details', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11);

    if (data.street || data.city) {
      doc.text(`Address: ${data.street || ''} ${data.buildingNumber || ''}, ${data.city || ''}`);
    }
    if (data.rooms) doc.text(`Rooms: ${data.rooms}`);
    if (data.area) doc.text(`Area: ${data.area} sqm`);
    if (data.floor) doc.text(`Floor: ${data.floor}`);
    if (data.propertyEssence) doc.text(`Type: ${data.propertyEssence}`);

    doc.moveDown();

    // Client Info
    if (data.clientName) {
      doc.fontSize(16).text('Client Information', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11);
      doc.text(`Client: ${data.clientName}`);
      if (data.visitDate) doc.text(`Visit Date: ${data.visitDate}`);
      doc.moveDown();
    }

    // Valuation Info
    if (data.valuationDate || data.referenceNumber) {
      doc.fontSize(16).text('Valuation Information', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11);
      if (data.valuationDate) doc.text(`Valuation Date: ${data.valuationDate}`);
      if (data.referenceNumber) doc.text(`Reference Number: ${data.referenceNumber}`);
      doc.moveDown();
    }

    // Land Registry Data
    if (data.gush || data.parcel) {
      doc.fontSize(16).text('Land Registry', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11);
      if (data.gush) doc.text(`Gush: ${data.gush}`);
      if (data.parcel) doc.text(`Parcel: ${data.parcel}`);
      if (data.subParcel) doc.text(`Sub-Parcel: ${data.subParcel}`);
      doc.moveDown();
    }

    // Extracted Data Summary
    if (data.extractedData && Object.keys(data.extractedData).length > 0) {
      doc.fontSize(16).text('AI Extracted Data', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10);
      doc.text(JSON.stringify(data.extractedData, null, 2), {
        width: 410
      });
      doc.moveDown();
    }

    // GIS Analysis
    if (data.gisAnalysis) {
      doc.fontSize(16).text('GIS Analysis', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11);
      if (data.gisAnalysis.coordinates) {
        doc.text(`Coordinates (ITM): ${data.gisAnalysis.coordinates.x}, ${data.gisAnalysis.coordinates.y}`);
        doc.text(`Coordinates (WGS84): ${data.gisAnalysis.coordinates.lat}, ${data.gisAnalysis.coordinates.lng}`);
      }
      doc.moveDown();
    }

    // Footer
    doc.fontSize(10)
      .text('Generated by Shamay.AI - Real Estate Valuation Platform', 72, doc.page.height - 50, {
        align: 'center',
        width: doc.page.width - 144
      });

    // Finalize PDF
    doc.end();

    console.log(`✅ PDF generated successfully for session: ${sessionId}`);

  } catch (error) {
    console.error('❌ Error generating PDF:', error);
    
    // If headers not sent yet, return error as JSON
    if (!res.headersSent) {
      res.status(500).json({
        success: false,
        error: 'Failed to generate PDF',
        details: error.message
      });
    }
  }
});

module.exports = router;

